# Generated by Django 5.2.8 on 2025-11-21 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='infrastructure_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/')),
                ('type', models.CharField(max_length=50)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='home.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='person_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=100)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('adopted_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('adopted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_details', to='home.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='org_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_description', models.TextField()),
                ('proof', models.FileField(upload_to='videos/')),
                ('prescription', models.FileField(default='no data', upload_to='prescription/')),
                ('amount', models.IntegerField()),
                ('amount_got', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('raised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_details', to='home.organisation')),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_details', to='organisation.person_list')),
            ],
        ),
    ]
