# Generated by Django 5.2.8 on 2025-11-21 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=50)),
                ('approval', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=50)),
                ('postal_code', models.IntegerField(null=True)),
                ('licence', models.CharField(max_length=100)),
                ('licence_image', models.FileField(upload_to='organisation/')),
                ('email', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('landmark', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_details', to='home.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='home.login')),
            ],
        ),
    ]
