# Generated by Django 5.2.8 on 2025-11-21 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adoption_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30)),
                ('adopted_date', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=30)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_person_details', to='organisation.person_list')),
                ('request_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_person', to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Charity_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_given', models.IntegerField(default=0)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_details', to='organisation.org_fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_provider_details', to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='fund_complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('proof', models.FileField(upload_to='bill/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply', models.CharField(max_length=100, null=True)),
                ('replied_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('complaint_against', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_complaint_org', to='home.organisation')),
                ('complaint_raised', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_complaint_user', to='organisation.org_fund')),
                ('complainted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complainted_person', to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Person_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='male', max_length=100)),
                ('image', models.ImageField(upload_to='uploads')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.CharField(max_length=100)),
                ('sub_district', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
                ('landmark', models.TextField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('adopted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.organisation')),
                ('uploaded', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_person', to='home.user')),
            ],
        ),
    ]
